name: Unit Test

# Trigger the workflow when a push or pull request is made to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        # Step 1: Checkout the code from the repository
        - name: Checkout code
          uses: actions/checkout@v2

        # Step 2: Set up Python
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.10

        # Step 3: Install dependencies
        - name: Install dependencies
          run:
            python -m pip install --upgrade pip
            pip install -r requirement.txt

        # Step 4: Run tests
        - name: Run tests
          run: pytest
            
